## Step 1. Import libraries

In [1]:
from pulp import *
#pulpTestAll()  # test solvers
import pandas as pd
import numpy as np
import scipy as sci

## Step 2: Define a variable using LpProblem to represent the optimization problem



In [3]:
question1 = LpProblem("question1",LpMinimize)

## Step 3: Define decision variables using LpVariable


In [4]:
xae=LpVariable("xae",lowBound=0,upBound=0,cat='Integer')# can't produce extrafine
xaf=LpVariable("xaf",lowBound=0,upBound=999999,cat='Integer')
xam=LpVariable("xam",lowBound=0,upBound=999999,cat='Integer')
xac=LpVariable("xac",lowBound=0,upBound=999999,cat='Integer')
xbe=LpVariable("xbe",lowBound=0,upBound=999999,cat='Integer')
xbf=LpVariable("xbf",lowBound=0,upBound=999999,cat='Integer')
xbm=LpVariable("xbm",lowBound=0,upBound=999999,cat='Integer')
xbc=LpVariable("xbc",lowBound=0,upBound=999999,cat='Integer')
xce=LpVariable("xce",lowBound=0,upBound=999999,cat='Integer')
xcf=LpVariable("xcf",lowBound=0,upBound=999999,cat='Integer')
xcm=LpVariable("xcm",lowBound=0,upBound=999999,cat='Integer')
xcc=LpVariable("xcc",lowBound=0,upBound=999999,cat='Integer')
xde=LpVariable("xde",lowBound=0,upBound=0,cat='Integer')# can't produce extrafine
xdf=LpVariable("xdf",lowBound=0,upBound=999999,cat='Integer')
xdm=LpVariable("xdm",lowBound=0,upBound=999999,cat='Integer')
xdc=LpVariable("xdc",lowBound=0,upBound=999999,cat='Integer')
xee=LpVariable("xee",lowBound=0,upBound=999999,cat='Integer')
xef=LpVariable("xef",lowBound=0,upBound=999999,cat='Integer')
xem=LpVariable("xem",lowBound=0,upBound=999999,cat='Integer')
xec=LpVariable("xec",lowBound=0,upBound=999999,cat='Integer')
xfe=LpVariable("xfe",lowBound=0,upBound=999999,cat='Integer')
xff=LpVariable("xff",lowBound=0,upBound=999999,cat='Integer')
xfm=LpVariable("xfm",lowBound=0,upBound=999999,cat='Integer')
xfc=LpVariable("xfc",lowBound=0,upBound=999999,cat='Integer')
xge=LpVariable("xge",lowBound=0,upBound=999999,cat='Integer')
xgf=LpVariable("xgf",lowBound=0,upBound=999999,cat='Integer')
xgm=LpVariable("xgm",lowBound=0,upBound=999999,cat='Integer')
xgc=LpVariable("xgc",lowBound=0,upBound=999999,cat='Integer')

## Step 4: Add the objective function and constraints to the LP problem using += operator

In [5]:
#read external data - production cost
production = pd.read_excel('C:/OMM500N/Filatoi tables.xlsx',sheet_name='production cost')

In [6]:
production_array = production.fillna(0).values #the production cost matrix
production_array

array([[ 0.  , 13.  , 10.65,  9.6 ],
       [17.4 , 14.1 , 11.2 ,  9.45],
       [17.4 , 14.22, 11.  ,  9.5 ],
       [ 0.  , 14.3 , 11.25,  9.6 ],
       [17.5 , 13.8 , 11.4 ,  9.6 ],
       [18.25, 13.9 , 11.4 ,  8.9 ],
       [19.75, 13.9 , 10.75,  9.4 ]])

In [7]:
round_trip=[30,40,80,70,70,0,50]
transportation = pd.read_excel('C:/OMM500N/Filatoi tables.xlsx',sheet_name='transportation cost')
transportation_array = transportation.values
transportation_array

array([[0.3 , 0.3 , 0.45, 0.45],
       [0.4 , 0.4 , 0.6 , 0.6 ],
       [0.8 , 0.8 , 1.2 , 1.2 ],
       [0.7 , 0.7 , 1.05, 1.05],
       [0.7 , 0.7 , 1.05, 1.05],
       [0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.5 , 0.75, 0.75]])

In [8]:
a = transportation_array + production_array
a

array([[ 0.3 , 13.3 , 11.1 , 10.05],
       [17.8 , 14.5 , 11.8 , 10.05],
       [18.2 , 15.02, 12.2 , 10.7 ],
       [ 0.7 , 15.  , 12.3 , 10.65],
       [18.2 , 14.5 , 12.45, 10.65],
       [18.25, 13.9 , 11.4 ,  8.9 ],
       [20.25, 14.4 , 11.5 , 10.15]])

In [9]:
time = pd.read_excel('C:/OMM500N/Filatoi tables.xlsx',sheet_name='time').fillna(0).values
time

array([[0.   , 0.4  , 0.375, 0.25 ],
       [0.7  , 0.5  , 0.35 , 0.25 ],
       [0.675, 0.45 , 0.4  , 0.25 ],
       [0.   , 0.45 , 0.35 , 0.2  ],
       [0.65 , 0.45 , 0.4  , 0.25 ],
       [0.625, 0.5  , 0.425, 0.425],
       [0.7  , 0.45 , 0.35 , 0.4  ]])

In [10]:
question1+=(0.3*xae+13.3*xaf+11.1*xam+10.05*xac+17.8*xbe+14.5*xbf+
        11.8*xbm+10.05*xbc+18.2*xce+15.02*xcf+12.2*xcm+10.7*xcc + 0.7*xde + 15*xdf + 12.3*xdm + 10.65*xdc + 18.2*xee + 14.5*xef + 
           12.45*xem + 10.65*xec + 18.25*xfe + 13.9*xff + 11.4*xfm + 8.9*xfc + 20.25*xge + 14.4*xgf 
          + 11.5*xgm + 10.15*xgc)

question1 += xae+xbe+xce+xde+xee+xfe+xge == 25000
question1 +=  xaf+xbf+xcf+xdf+xef+xff+xgf ==26000
question1 += xam+xbm+xcm+xdm+xem+xfm+xgm  ==28000
question1 +=  xac+xbc+xcc+xdc+xec+xfc+xgc ==28000
question1 += 0*xae + 0.4*xaf +0.375*xam + 0.25*xac  <=2500
question1 +=0.7*xbe + 0.5*xbf + 0.35*xbm + 0.25*xbc <=3000
question1 +=  0.675*xce + 0.45*xcf + 0.4*xcm +0.25*xcc <=2500
question1 += 0*xde + 0.45*xdf + 0.35*xdm + 0.2*xdc  <=2600
question1 += 0.65*xee + 0.45*xef + 0.4*xem + 0.25*xec  <=2500
question1 += 0.625*xfe + 0.5*xff + 0.425*xfm + 0.425*xfc  <=38000
question1 += 0.7*xge +0.45*xgf +0.35*xgm + 0.4*xgc  <=2500


In [11]:
question1

question1:
MINIMIZE
10.05*xac + 0.3*xae + 13.3*xaf + 11.1*xam + 10.05*xbc + 17.8*xbe + 14.5*xbf + 11.8*xbm + 10.7*xcc + 18.2*xce + 15.02*xcf + 12.2*xcm + 10.65*xdc + 0.7*xde + 15*xdf + 12.3*xdm + 10.65*xec + 18.2*xee + 14.5*xef + 12.45*xem + 8.9*xfc + 18.25*xfe + 13.9*xff + 11.4*xfm + 10.15*xgc + 20.25*xge + 14.4*xgf + 11.5*xgm + 0.0
SUBJECT TO
_C1: xae + xbe + xce + xde + xee + xfe + xge = 25000

_C2: xaf + xbf + xcf + xdf + xef + xff + xgf = 26000

_C3: xam + xbm + xcm + xdm + xem + xfm + xgm = 28000

_C4: xac + xbc + xcc + xdc + xec + xfc + xgc = 28000

_C5: 0.25 xac + 0.4 xaf + 0.375 xam <= 2500

_C6: 0.25 xbc + 0.7 xbe + 0.5 xbf + 0.35 xbm <= 3000

_C7: 0.25 xcc + 0.675 xce + 0.45 xcf + 0.4 xcm <= 2500

_C8: 0.2 xdc + 0.45 xdf + 0.35 xdm <= 2600

_C9: 0.25 xec + 0.65 xee + 0.45 xef + 0.4 xem <= 2500

_C10: 0.425 xfc + 0.625 xfe + 0.5 xff + 0.425 xfm <= 38000

_C11: 0.4 xgc + 0.7 xge + 0.45 xgf + 0.35 xgm <= 2500

VARIABLES
0 <= xac <= 999999 Integer
xae = 0 Integer
0 <= xaf <= 999

## Step 5: Run solver



In [12]:
question1.writeLP("quesion1.lp") #optional
question1.solve()
print("Status:",LpStatus[question1.status])

Status: Optimal


In [13]:
for v in question1.variables():
    print(v.name, "=", v.varValue,"\tReduced Cost =", v.dj)
    
print("Total revenue=", value(question1.objective))

xac = 0.0 	Reduced Cost = 10.05
xae = 0.0 	Reduced Cost = 0.3
xaf = 6250.0 	Reduced Cost = 13.3
xam = 0.0 	Reduced Cost = 11.1
xbc = 0.0 	Reduced Cost = 10.05
xbe = 4285.0 	Reduced Cost = 17.8
xbf = 0.0 	Reduced Cost = 14.5
xbm = 1.0 	Reduced Cost = 11.8
xcc = 0.0 	Reduced Cost = 10.7
xce = 3703.0 	Reduced Cost = 18.2
xcf = 0.0 	Reduced Cost = 15.02
xcm = 1.0 	Reduced Cost = 12.2
xdc = 0.0 	Reduced Cost = 10.65
xde = 0.0 	Reduced Cost = 0.7
xdf = 2.0 	Reduced Cost = 15.0
xdm = 2039.0 	Reduced Cost = 12.3
xec = 0.0 	Reduced Cost = 10.65
xee = 3846.0 	Reduced Cost = 18.2
xef = 0.0 	Reduced Cost = 14.5
xem = 0.0 	Reduced Cost = 12.45
xfc = 28000.0 	Reduced Cost = 8.9
xfe = 13166.0 	Reduced Cost = 18.25
xff = 19748.0 	Reduced Cost = 13.9
xfm = 18817.0 	Reduced Cost = 11.4
xgc = 0.0 	Reduced Cost = 10.15
xge = 0.0 	Reduced Cost = 20.25
xgf = 0.0 	Reduced Cost = 14.4
xgm = 7142.0 	Reduced Cost = 11.5
Total revenue= 1382547.0


In [17]:
#two extreme cases
f=[18.25, 13.9 , 11.4 ,  8.9 ]
f_max = [1.05*i for i in f]
f_min = [0.95*i for i in f]
f_delta = [0.05*i for i in f]
print(f_max)
print(f_min)
print(f_delta)

[19.1625, 14.595, 11.97, 9.345]
[17.3375, 13.205, 10.83, 8.455]
[0.9125000000000001, 0.6950000000000001, 0.5700000000000001, 0.44500000000000006]
